name: PR checks
on:
  push:
    branches: [master]
jobs:
  use-reusable-workflow:
    uses: honeybadgersoftware/ci-cd/.github/workflows/on-push.yml@master
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      gh_token: ${{ secrets.GH_TOKEN }}